{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinipsum
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinipsum_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinipsum/shinipsum_{{ version }}.tar.gz
  sha256: f690000b73021134e7b88ba699b22e696df68a5ad7210d3aa20bbc0a130a2435

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dt
    - r-attempt
    - r-dygraphs
    - r-ggplot2 >=3.0.0
    - r-magrittr
    - r-plotly
  run:
    - r-base
    - r-dt
    - r-attempt
    - r-dygraphs
    - r-ggplot2 >=3.0.0
    - r-magrittr
    - r-plotly

test:
  commands:
    - $R -e "library('shinipsum')"           # [not win]
    - "\"%R%\" -e \"library('shinipsum')\""  # [win]

about:
  home: https://github.com/Thinkr-open/shinipsum
  license: MIT
  summary: Prototype your 'shiny' apps quickly with these Lorem-Ipsum helper functions. Generate
    random elements for 'shiny' outputs that can be used as placeholder in your application.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
